create table przedmiot(nazwa VARCHAR(20)not null,idprzedmiot int, PRIMARY KEY (idprzedmiot));
create table nauczyciel(imie VARCHAR(20)not null,nazwisko VARCHAR(20)not null,adres VARCHAR(20)not null,mail VARCHAR(20)not null,idnauczyciel int, PRIMARY KEY (idnauczyciel));
create table klasa(nazwa VARCHAR(20)not null,idklasa int, PRIMARY KEY (idklasa));
create table uczen(imie VARCHAR(20)not null,nazwisko VARCHAR(20)not null,adres VARCHAR(20)not null,iduczen int, idklasa int,PRIMARY KEY (iduczen),FOREIGN key(idklasa)REFERENCES klasa(idklasa));
create table nauczanie(idprzedmiot int, idnauczyciel int,FOREIGN key(idprzedmiot)REFERENCES przedmiot(idprzedmiot),FOREIGN key(idnauczyciel)REFERENCES nauczyciel(idnauczyciel));
create table nauczanie_w_klasie(idklasa int, idnauczyciel int,FOREIGN key(idklasa)REFERENCES klasa(idklasa),FOREIGN key(idnauczyciel)REFERENCES nauczyciel(idnauczyciel));
Insert into przedmiot (nazwa , idprzedmiot ) VALUES ('polski',1);
Insert into przedmiot (nazwa , idprzedmiot ) VALUES ('matematyka',2);
Insert into przedmiot (nazwa , idprzedmiot ) VALUES ('wf',3);
Insert into przedmiot (nazwa , idprzedmiot ) VALUES ('informatyka',4);
Insert into przedmiot (nazwa , idprzedmiot ) VALUES ('chemia',5);
Insert into nauczyciel (imie,nazwisko,adres,mail,idnauczyciel) values ('pedagog','waldemar','chelm','aaaaaa',1);
Insert into nauczyciel (imie,nazwisko,adres,mail,idnauczyciel) values ('jan','pop','lublin','aaabaaa',2);
Insert into nauczyciel (imie,nazwisko,adres,mail,idnauczyciel) values ('pawel','ek','warszawa','aaseaaa',3);
Insert into nauczyciel (imie,nazwisko,adres,mail,idnauczyciel) values ('piotr','pat','zamosc','cbaaa',4);
Insert into nauczyciel (imie,nazwisko,adres,mail,idnauczyciel) values ('patryk','ryk','zakopane','aagfeaa',5);
Insert into nauczyciel (imie,nazwisko,adres,mail,idnauczyciel) values ('andzej','patyk','miasto','fhyfsaa',6);
Insert into klasa (nazwa , idklasa ) VALUES ('6a',1);
Insert into klasa (nazwa , idklasa ) VALUES ('6b',2);
Insert into klasa (nazwa , idklasa ) VALUES ('6c',3);
Insert into klasa (nazwa , idklasa ) VALUES ('7b',4);
Insert into klasa (nazwa , idklasa ) VALUES ('7a',5);
Insert into uczen (imie,nazwisko,adres,iduczen) values ('jan','kowalski','chelm',1);
Insert into uczen (imie,nazwisko,adres,iduczen) values ('mango','kiwi','chelm',2);
Insert into uczen (imie,nazwisko,adres,iduczen) values ('rower','rek','chelm',3);
Insert into uczen (imie,nazwisko,adres,iduczen) values ('pat','ryczek','chelm',4);
Insert into uczen (imie,nazwisko,adres,iduczen) values ('papryka','patyk','chelm',5);
Insert into uczen (imie,nazwisko,adres,iduczen) values ('ba','za','chelm',6);
Insert into uczen (imie,nazwisko,adres,iduczen) values ('mle','ko','chelm',7);
Insert into uczen (imie,nazwisko,adres,iduczen) values ('pios','enka','chelm',8);
Insert into uczen (imie,nazwisko,adres,iduczen) values ('andrzej','nowak','chelm',9);
Insert into uczen (imie,nazwisko,adres,iduczen) values ('jerzy','lisc','chelm',10);
Insert into uczen (imie,nazwisko,adres,iduczen) values ('klawia','tura','chelm',11);
Insert into uczen (imie,nazwisko,adres,iduczen) values ('patryk','popek','chelm',12);
update  uczen set idklasa=1 where iduczen=1;
update  uczen set idklasa=2 where iduczen=2;
update  uczen set idklasa=1 where iduczen=3;
update  uczen set idklasa=3 where iduczen=4;
update  uczen set idklasa=5 where iduczen=5;
update  uczen set idklasa=5 where iduczen=6;
update  uczen set idklasa=4 where iduczen=7;
update  uczen set idklasa=4 where iduczen=8;
update  uczen set idklasa=3 where iduczen=9;
update  uczen set idklasa=2 where iduczen=10;
update  uczen set idklasa=3 where iduczen=11;
update  uczen set idklasa=1 where iduczen=12;
Insert into nauczanie (idnauczyciel , idprzedmiot ) VALUES (1,5);
Insert into nauczanie (idnauczyciel , idprzedmiot ) VALUES (2,4);
Insert into nauczanie (idnauczyciel , idprzedmiot ) VALUES (1,3);
Insert into nauczanie (idnauczyciel , idprzedmiot ) VALUES (4,5);
Insert into nauczanie (idnauczyciel , idprzedmiot ) VALUES (3,1);
Insert into nauczanie (idnauczyciel , idprzedmiot ) VALUES (6,1);
Insert into nauczanie (idnauczyciel , idprzedmiot ) VALUES (1,5);
Insert into nauczanie (idnauczyciel , idprzedmiot ) VALUES (2,5);
Insert into nauczanie (idnauczyciel , idprzedmiot ) VALUES (6,3);
Insert into nauczanie (idnauczyciel , idprzedmiot ) VALUES (1,4);
Insert into nauczanie (idnauczyciel , idprzedmiot ) VALUES (2,4);

Insert into nauczanie_w_klasie (idnauczyciel , idklasa ) VALUES (1,4);
Insert into nauczanie_w_klasie (idnauczyciel , idklasa ) VALUES (3,1);
Insert into nauczanie_w_klasie (idnauczyciel , idklasa ) VALUES (6,3);
Insert into nauczanie_w_klasie (idnauczyciel , idklasa ) VALUES (6,4);
Insert into nauczanie_w_klasie (idnauczyciel , idklasa ) VALUES (4,4);
Insert into nauczanie_w_klasie (idnauczyciel , idklasa ) VALUES (4,3);
Insert into nauczanie_w_klasie (idnauczyciel , idklasa ) VALUES (4,5);
Insert into nauczanie_w_klasie (idnauczyciel , idklasa ) VALUES (1,1);
Insert into nauczanie_w_klasie (idnauczyciel , idklasa ) VALUES (1,5);
Insert into nauczanie_w_klasie (idnauczyciel , idklasa ) VALUES (3,2);
Insert into nauczanie_w_klasie (idnauczyciel , idklasa ) VALUES (2,4);
Insert into nauczanie_w_klasie (idnauczyciel , idklasa ) VALUES (2,1);
Insert into nauczanie_w_klasie (idnauczyciel , idklasa ) VALUES (2,5);
select u.imie, u.nazwisko from uczen u join klasa k on u.idklasa = k.idklasa  where k.nazwa='6a';
select  n.imie , n.nazwisko from nauczyciel n join nauczanie_w_klasie nk on nk.idnauczyciel=n.idnauczyciel join klasa k on k.idklasa=nk.idklasa join uczen u on u.idklasa=k.idklasa where u.iduczen=1;
select  n.imie , n.nazwisko from nauczyciel n join nauczanie m on n.idnauczyciel = m.idnauczyciel join przedmiot p on p.idprzedmiot=m.idprzedmiot where p.nazwa='wf';
select p.nazwa from przedmiot p where not  EXISTS(select n.idprzedmiot from nauczanie n where  n.idprzedmiot=p.idprzedmiot);