//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Baza.cpp
//  @ Date : 28.04.2022
//  @ Author :
//
//


#include "Baza.h"
#include "Towar.h"
#include "Rower.h"
#include "Hulajnoga.h"
#include <iostream>
#include <string>
#include <map>
#include "Konto.h"
using namespace std;

Baza::Baza()
{
    nazwy.push_back(Hulajnoga("Elektryczna",100,false));
    stan.push_back(10);
    nazwy.push_back(Rower("Miejski",200,false));
    stan.push_back(10);
}

void Baza::PokazSzczegoloweDane()
{

    cout<<"Nazwa "<<'\t'<<"Cena"<<'\t'<<"ilosc"<<'\t'<<"czyZepsuty"<<'\n';
    for( int i=0;i<nazwy.size();i++)
    {
       if(stan.at(i)>0)
       {
           cout<<nazwy.at(i).getName()<<" "<<nazwy.at(i).getPrice()<<" "<<stan.at(i)<<" "<<nazwy.at(i).getBool()<<'\n';
       }
    }
}
void Baza::SprawdzDostepnoscKatalogu()
{
    cout<<"Nazwa "<<'\t'<<"Cena"<<'\n';
    for( int i=0;i<nazwy.size();i++)
    {
       if(stan.at(i)>0)
       {
           cout<<nazwy.at(i).getName()<<" "<<nazwy.at(i).getPrice()<<'\n';
       }
    }

}
void Baza::znajdz(std::string name,float cena)
{
    for( int i=0;i<nazwy.size();i++)
    {
       if(nazwy.at(i).getName()==name)
       {
            nazwy.at(i).setPrice(cena);
            cout<<"Zmieniono cene "<<'\n';
            return;
       }
       if(i==nazwy.size()-1)
       {
            cout<<"Transakcja niezrealizowana, brak wpisu o towarze w bazie "<<'\n';
            return;
       }
    }
}

Konto Baza::zmienStan(std::string name,Konto konto) {
    for( int i=0;i<nazwy.size();i++)
    {
       if(nazwy.at(i).getName()==name)
       {
            nazwy.at(i).setBool(false);
            float x=konto.getwartosc()+10;
            konto.setwartosc(x);
            cout<<"Naprawiono rower "<<'\n';
             return konto;

       }
       if(i==nazwy.size()-1)
       {
            cout<<"Transakcja niezrealizowana, zerowy stan towaru na skladzie "<<'\n';
             return konto;
       }
    }
    return konto;

}
Konto Baza::dodaj(std::string name,Konto konto,int ilosc,float cena)
{
    for( int i=0;i<nazwy.size();i++)
    {
       if(nazwy.at(i).getName()==name)
       {
            if(nazwy.at(i).getPrice()*ilosc>konto.getwartosc())
            {
                cout<<"Transakcja niezrealizowana, brak funduszy w kasie sklepu "<<'\n';
                  return konto;
            }
            else
            {
                float x=konto.getwartosc()-nazwy.at(i).getPrice()*ilosc;
                konto.setwartosc(x);
                cout<<"Odkupiono towar "<<'\n';
                int a=stan.at(i);
                stan.at(i)=a+ilosc;
                  return konto;
            }
       }
       if(i==nazwy.size()-1)
       {
            if(konto.getwartosc()<cena*ilosc)
            {
                cout<<"Transakcja niezrealizowana, brak funduszy w kasie sklepu "<<'\n';
                return konto;
            }
            else
            {
                cout<<"Odkupiono towar "<<'\n';
                float x=konto.getwartosc()-cena*ilosc;
                konto.setwartosc(x);
                nazwy.push_back(Towar(name,cena,true));
                stan.push_back(ilosc);
                  return konto;
            }
       }
    }
      return konto;
}
Konto Baza::odejmij(std::string name,Konto konto)
{
    for( int i=0;i<nazwy.size();i++)
    {
       if(nazwy.at(i).getName()==name)
       {
           if(stan.at(i)>0)
           {
                cout<<"Sprzedano towar "<<'\n';
                float x=konto.getwartosc()+nazwy.at(i).getPrice();
                konto.setwartosc(x);
                stan.at(i)--;
                  return konto;
           }
           else
           {
               cout<<"Transakcja niezrealizowana, zerowy stan towaru na skladzie "<<'\n';
                 return konto;
           }
       }
       if(i==nazwy.size()-1)
       {
            cout<<"Transakcja niezrealizowana, zerowy stan towaru na skladzie "<<'\n';
                return konto;
       }
    }
     return konto;
}

