//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : FirmaZaopatrzeniowa.h
//  @ Date : 28.04.2022
//  @ Author :
//
//


#if !defined(_FIRMAZAOPATRZENIOWA_H)
#define _FIRMAZAOPATRZENIOWA_H
#include "Towar.h"
#include <string>
#include "Baza.h"
#include "Konto.h"
#include <tuple>


class FirmaZaopatrzeniowa {
public:
	std::tuple<Baza,Konto> ZamowTowar(std::string name,Baza baza,Konto konto,int ilosc,float cena);
	FirmaZaopatrzeniowa();
private:

};

#endif  //_FIRMAZAOPATRZENIOWA_H
