//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : FirmaZaopatrzeniowa.cpp
//  @ Date : 28.04.2022
//  @ Author :
//
//


#include "FirmaZaopatrzeniowa.h"
#include <string>
#include "Baza.h"
#include "Konto.h"
#include <tuple>
std::tuple<Baza,Konto> FirmaZaopatrzeniowa::ZamowTowar(std::string name,Baza baza,Konto konto,int ilosc,float cena)
{
   Konto k= baza.dodaj(name,konto,ilosc,cena);
    return std::make_pair(baza,k);

}


FirmaZaopatrzeniowa::FirmaZaopatrzeniowa()
{

}

