//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Hulajnoga.h
//  @ Date : 28.04.2022
//  @ Author :
//
//


#if !defined(_HULAJNOGA_H)
#define _HULAJNOGA_H

#include "Towar.h"
#include <string>

class Hulajnoga : public Towar {
public:
    Hulajnoga(std::string name,float price,bool czyZepsuty);
};

#endif  //_HULAJNOGA_H
