//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Klient.h
//  @ Date : 28.04.2022
//  @ Author :
//
//


#if !defined(_KLIENT_H)
#define _KLIENT_H

#include "Baza.h"
#include "Wlasciciel.h"
#include<String>

class Klient {
public:
	Wlasciciel kupRower(std::string marka,Wlasciciel wlasciciel,float cena,int ilosc);
	Wlasciciel naprawRower(std::string marka, Wlasciciel wlasciciel);
	Wlasciciel zwrocRower(std::string marka, Wlasciciel wlasciciel,float cena,int ilosc);
	void zobaczStan(Wlasciciel wlasciciel);
	Klient();

};

#endif  //_KLIENT_H
