//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Konto.h
//  @ Date : 28.04.2022
//  @ Author :
//
//


#if !defined(_KONTO_H)
#define _KONTO_H


class Konto {
public:
	void setwartosc(float wartosc);
	float getwartosc();
	Konto (float wartosc);
	Konto();

private:
	float wartosc;
};

#endif  //_KONTO_H
