//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Konto.cpp
//  @ Date : 28.04.2022
//  @ Author :
//
//


#include "Konto.h"

void Konto::setwartosc(float wartosc)
{
    this->wartosc=wartosc;
}

float Konto::getwartosc()
{
    return wartosc;
}
Konto::Konto(float wartosc)
{
    this->wartosc=wartosc;
}
Konto::Konto()
{

}


