//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pracownik.cpp
//  @ Date : 28.04.2022
//  @ Author :
//
//


#include "Pracownik.h"
#include <string>
#include "Baza.h"
#include "Konto.h"

Pracownik::Pracownik(std::string name,int number)
{
    this->name=name;
    this->number=number;
}



