//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pracownik.h
//  @ Date : 28.04.2022
//  @ Author :
//
//


#if !defined(_PRACOWNIK_H)
#define _PRACOWNIK_H
#include<string>
#include "Baza.h"
#include "Konto.h"



class Pracownik {
public:
   void wykonajPrace(std::string name,bool flag,Baza* baza,Konto *konto);
    Pracownik(std::string name,int number);
private:
	std::string name;
	int number;
};

#endif  //_PRACOWNIK_H
