//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Rower.h
//  @ Date : 28.04.2022
//  @ Author :
//
//


#if !defined(_ROWER_H)
#define _ROWER_H

#include "Towar.h"

class Rower : public Towar {
    public:
    Rower(std::string name,float price,bool czyZepsuty);
};

#endif  //_ROWER_H
