//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Serwisant.h
//  @ Date : 28.04.2022
//  @ Author :
//
//


#if !defined(_SERWISANT_H)
#define _SERWISANT_H

#include "Pracownik.h"
#include "Baza.h"
#include "Konto.h"

class Serwisant : public Pracownik {
public:
    Serwisant(std::string name,int number);
    std::tuple<Baza,Konto> wykonajPrace(std::string name,bool flag,Baza baza,Konto konto);
};

#endif  //_SERWISANT_H
