//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Towar.h
//  @ Date : 28.04.2022
//  @ Author :
//
//


#if !defined(_TOWAR_H)
#define _TOWAR_H
#include <string>


class Towar {
public:
	void setPrice(float price);
	bool getBool();
	std::string getName();
	float getPrice();
	Towar(std::string name,float price,bool czyZepsuty);
	void setBool(bool flag);
    std::string setName(std::string name);
private:
	std::string name;
	float price;
	bool czyZepsuty;
};

#endif  //_TOWAR_H
