//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Towar.cpp
//  @ Date : 28.04.2022
//  @ Author :
//
//


#include "Towar.h"
#include <string>

void Towar::setPrice(float price) {
    this->price=price;
}

bool Towar::getBool() {
    return czyZepsuty;
}
void Towar::setBool(bool flag)
{
    this->czyZepsuty=flag;
}

std::string Towar::setName(std::string name)
{
    this->name=name;
}
Towar::Towar(std::string name,float price,bool czyZepsuty)
{
    this->czyZepsuty=czyZepsuty;
    this->price=price;
    this->name=name;
}
std::string Towar::getName()
{
    return name;
}
float Towar::getPrice()
{
    return price;
}

