//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Wlasciciel.h
//  @ Date : 28.04.2022
//  @ Author :
//
//


#if !defined(_WLASCICIEL_H)
#define _WLASCICIEL_H

#include "Baza.h"
#include "Konto.h"
#include "Pracownik.h"
#include "historiatransakcji.h"

#include <string>
#include <vector>

class Wlasciciel {
public:

	void ZmienCene(std::string nazwa,float cena);

	Wlasciciel(std::string name,Baza baza,Konto konto);
    Konto getKonto();
    Baza getBaza();
    void setBaza(Baza baza);
    void setKonto(Konto konto);
    void showHistory();
    void addHistory(std::string name);




private:
    std::vector <HistoriaTransakcji> hisT;
	std::string name;
	Baza baza;
	Konto konto;
};

#endif  //_WLASCICIEL_H
