CREATE table plyta (tytul VARCHAR(20) not null, dlugosc INTEGER not null,idplyta int not null, PRIMARY KEY (idplyta));
CREATE table utwor (tytul VARCHAR(20) not null, gatunek VARCHAR(20) not null,idplyta int not null,idutwor int not null ,PRIMARY KEY (idutwor),FOREIGN KEY(idplyta) REFERENCES plyta(idplyta));
CREATE table wydawnictwo (nazwa VARCHAR(30) not null, adres VARCHAR(30) not null,idwydawnictwo int not null, PRIMARY KEY (idwydawnictwo));
CREATE table muzyk (pseudonim VARCHAR(20) not null, nazwisko VARCHAR(20) not null, instrument VARCHAR(20),idwydawnictwo int not null,idmuzyk int not null   ,PRIMARY KEY (idmuzyk),FOREIGN KEY(idwydawnictwo) REFERENCES wydawnictwo(idwydawnictwo));
CREATE table wykonawcy (idutwor int not null, idmuzyk int ,FOREIGN KEY(idutwor) REFERENCES utwor(idutwor),FOREIGN KEY(idmuzyk) REFERENCES muzyk(idmuzyk));
INSERT into plyta (tytul,dlugosc,idplyta) values ('mlecze na lace', 3456,1);
INSERT into plyta (tytul,dlugosc,idplyta) values ('igla w stogu siana', 3906,2);
INSERT into plyta (tytul,dlugosc,idplyta) values ('wycieczka rowerowa', 2606,3);
INSERT into utwor (tytul,gatunek ,idplyta,idutwor) values ('pop stars','kpop',1,1);
INSERT into utwor (tytul,gatunek ,idplyta,idutwor) values ('more','pop',1,2);
INSERT into utwor (tytul,gatunek ,idplyta,idutwor) values ('varriors','rap',3,3);
INSERT into utwor (tytul,gatunek ,idplyta,idutwor) values ('giants','regge',3,4);
INSERT into utwor (tytul,gatunek ,idplyta,idutwor) values ('rise','disco',1,5);
INSERT into wydawnictwo (nazwa,adres,idwydawnictwo) values ('cdproject','chelm',1);
INSERT into wydawnictwo (nazwa,adres,idwydawnictwo) values ('red','lublin',2);
INSERT into wydawnictwo (nazwa,adres,idwydawnictwo) values ('ubisoft','warszawa',3);
INSERT into muzyk (pseudonim,nazwisko,instrument,idwydawnictwo,idmuzyk) values ('popus','popek','puzon',2,1);
INSERT into muzyk (pseudonim,nazwisko,instrument,idwydawnictwo,idmuzyk) values ('steve','pop','puzon',1,2);
INSERT into muzyk (pseudonim,nazwisko,instrument,idwydawnictwo,idmuzyk) values ('macius','ek','puzon',3,3);
INSERT into muzyk (pseudonim,nazwisko,instrument,idwydawnictwo,idmuzyk) values ('colgista','pok','puzon',3,4);
INSERT into muzyk (pseudonim,nazwisko,instrument,idwydawnictwo,idmuzyk) values ('brudny','pat','puzon',3,5);
INSERT into muzyk (pseudonim,nazwisko,instrument,idwydawnictwo,idmuzyk) values ('pabilito','pek','puzon',1,6);
INSERT into wykonawcy (idutwor,idmuzyk) values (1,1);
INSERT into wykonawcy (idutwor,idmuzyk) values (1,2);
INSERT into wykonawcy (idutwor,idmuzyk) values (4,4);
INSERT into wykonawcy (idutwor,idmuzyk) values (2,5);
INSERT into wykonawcy (idutwor,idmuzyk) values (5,2);
INSERT into wykonawcy (idutwor,idmuzyk) values (5,3);
INSERT into wykonawcy (idutwor,idmuzyk) values (2,4);
INSERT into wykonawcy (idutwor,idmuzyk) values (4,1);
INSERT into wykonawcy (idutwor,idmuzyk) values (1,5);
Select muzyk.pseudonim from muzyk JOIN wykonawcy on wykonawcy.idmuzyk = muzyk.idmuzyk JOIN utwor on wykonawcy.idutwor=utwor.idutwor where  lower(utwor.tytul) like 'mor_';
Select plyta.tytul from plyta where not EXISTS(Select utwor.idplyta from utwor where plyta.idplyta=utwor.idplyta  );
Select wydawnictwo.nazwa from wydawnictwo join muzyk on wydawnictwo.idwydawnictwo = muzyk.idwydawnictwo where muzyk.pseudonim='steve';
Select utwor.tytul from utwor join  plyta on utwor.idplyta = plyta.idplyta where plyta.dlugosc>3000; 
